import { YoutubeVideoPlayer } from 'components/youtubePlayer'
import {useState} from "react";
import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const YOUTUBE_PLAYLIST_ITEMS_API = 'https://www.googleapis.com/youtube/v3/videos'

export async function getServerSideProps(){
  const res = await fetch(`${YOUTUBE_PLAYLIST_ITEMS_API}?part=snippet&chart=mostPopular&maxResults=25&key=${process.env.YOUTUBE_API_KEY}`);
  const data = await res.json();
  return{
    props: {
      data
    }  
  }
}

// const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  const [currentVideo, setCurrentVideo] = useState(data.items[0]);
  const [playing, setPlaying] = useState(false);
  console.log(data.items)
  return (
    <div>
      <div>
        <YoutubeVideoPlayer id={currentVideo.id} playing={playing}/> 
      </div>

      <div>
            <div>
              <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className={styles.main}>
                <h1 className={styles.title}>
                  playlist
                </h1>

                <ul className={styles.grid}>
                  {data.items.map((item)=>{
                    console.log('item', item);
                    const { id,snippet = {} } = item;
                    const { title, thumbnails = {}, resourceId} = snippet;
                    const { medium = {} } = thumbnails
                    return(
                      // 
                      <li key={id} className={styles.card}>
                        <a onClick={() => {setCurrentVideo(item); setPlaying(false)}}>
                          <p>
                            <img width={medium.width} height={medium.height} src={medium.url} alt=""/>
                          </p>
                          <h3>{title}</h3>
                        </a>
                      </li>
                    )
                  })}
                  
                </ul>
              </main>
            </div>
      </div>
    
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          playlist
        </h1>

        <ul className={styles.grid}>
          {data.items.map((item)=>{
            console.log('item', item);
            const { id,snippet = {} } = item;
            const { title, thumbnails = {}, resourceId} = snippet;
            const { medium = {} } = thumbnails
            return(
              // 
              <li key={id} className={styles.card}>
                <a>
                  <p>
                    <img width={medium.width} height={medium.height} src={medium.url} alt=""/>
                  </p>
                  <h3>{title}</h3>
                </a>
              </li>
            )
          })}
          
        </ul>
      </main> */}
    </div>
  )
}
